// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.InitialCreate.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Style", "IDE0053:Use expression body for lambda expressions", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.InitialCreate.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.InitialCreate.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.MinimalData.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.MinimalData.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.MinimalData.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Build", "CA1812:MockedPersonRepository is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "Instanciated by the DI", Scope = "type", Target = "~T:CrudPerson.DataLibrary.Internal.Repositories.MockedPersonRepository")]
[assembly: SuppressMessage("Build", "CA1812:PersonRepository is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "Instanciated by the DI", Scope = "type", Target = "~T:CrudPerson.DataLibrary.Internal.Repositories.PersonRepository")]
[assembly: SuppressMessage("Build", "CA1812:DatabaseContext is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this class is intended to contain only static members, make it static (Shared in Visual Basic).", Justification = "Instanciated by the DI", Scope = "type", Target = "~T:CrudPerson.DataLibrary.Internal.Data.DatabaseContext")]
[assembly: SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Map the definition of Microsoft.EntityFrameworkCore.DbContext.Set", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Data.IDatabaseContext.Set``1~Microsoft.EntityFrameworkCore.DbSet{``0}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.MinimalData.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.MinimalData.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.InitialCreate.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Generated code", Scope = "member", Target = "~M:CrudPerson.DataLibrary.Migrations.InitialCreate.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
