//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudPerson.CommonLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrudPerson.CommonLibrary.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person data is required.
        /// </summary>
        public static string ArgumentNullOrEmptyException_RequiredPersonData {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmptyException_RequiredPersonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The person identifier is required .
        /// </summary>
        public static string ArgumentNullOrEmptyException_RequiredPersonIdentifier {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmptyException_RequiredPersonIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person already exists with this identifier.
        /// </summary>
        public static string FailedActionException_AlreadyExistingPerson {
            get {
                return ResourceManager.GetString("FailedActionException_AlreadyExistingPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string FailedActionException_CreateActionName {
            get {
                return ResourceManager.GetString("FailedActionException_CreateActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FailedActionException_DeleteActionName {
            get {
                return ResourceManager.GetString("FailedActionException_DeleteActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string FailedActionException_EditActionName {
            get {
                return ResourceManager.GetString("FailedActionException_EditActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit of the person failed.
        /// </summary>
        public static string FailedActionException_EditPersonExceptionMessage {
            get {
                return ResourceManager.GetString("FailedActionException_EditPersonExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed action : {0} - {1}.
        /// </summary>
        public static string FailedActionException_FailedActionMessageFormat {
            get {
                return ResourceManager.GetString("FailedActionException_FailedActionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed action : {0} - {1} - Context data : {2}.
        /// </summary>
        public static string FailedActionException_FailedActionWithContentDataMessageFormat {
            get {
                return ResourceManager.GetString("FailedActionException_FailedActionWithContentDataMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the saving.
        /// </summary>
        public static string FailedActionException_SavingError {
            get {
                return ResourceManager.GetString("FailedActionException_SavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No person exists with this identifier.
        /// </summary>
        public static string FailedActionException_UnexistingPerson {
            get {
                return ResourceManager.GetString("FailedActionException_UnexistingPerson", resourceCulture);
            }
        }
    }
}
